config/routes.rb
Rails.application.routes.draw do
  resources :usuarios

  resources :livros

end

app/models/livro.rb
class Livro < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  before_action :set_livro, only: [:show, :edit, :update, :destroy]

  # GET /livros
  # GET /livros.json
  def index
    @livros = Livro.all
  end

  # GET /livros/1
  # GET /livros/1.json
  def show
  end

  # GET /livros/new
  def new
    @livro = Livro.new
  end

  # GET /livros/1/edit
  def edit
  end

  # POST /livros
  # POST /livros.json
  def create
    @livro = Livro.new(livro_params)

    respond_to do |format|
      if @livro.save
        format.html { redirect_to @livro, notice: 'Livro was successfully created.' }
        format.json { render :show, status: :created, location: @livro }
      else
        format.html { render :new }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /livros/1
  # PATCH/PUT /livros/1.json
  def update
    respond_to do |format|
      if @livro.update(livro_params)
        format.html { redirect_to @livro, notice: 'Livro was successfully updated.' }
        format.json { render :show, status: :ok, location: @livro }
      else
        format.html { render :edit }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /livros/1
  # DELETE /livros/1.json
  def destroy
    @livro.destroy
    respond_to do |format|
      format.html { redirect_to livros_url, notice: 'Livro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_livro
      @livro = Livro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def livro_params
      params.require(:livro).permit(:titulo, :nome, :descricao, :codigo, :sbn, :autor, :idioma, :paginacao, :imprenta, :palavras, :chave, :data_cadastro)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:matricula, :nome, :sobrenome, :endereco, :string, :telefone, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Biblioteca</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
	
	<%= link_to 'Biblioteca',  livros_path , class:"navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
	<ul class="nav navbar-nav">
	  
	  <li class=""><%= link_to 'Usuarios', usuarios_path %></li>
	  <li class=""><%= link_to 'Livros', livros_path %></li>
	</ul>
	<ul class="nav navbar-nav pull-right">
	  <li class=""><p>Sair<p></li>
	</ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>

<%= yield %>

</body>
</html>

app/views/livros/_form.html.erb
<%= simple_form_for(@livro) do |f| %>
  <% if @livro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@livro.errors.count, "error") %> prohibited this livro from being saved:</h2>

      <ul>
      <% @livro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_area :descricao %>
  </div>
  <div class="field">
    <%= f.label :codigo %><br>
    <%= f.text_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :sbn %><br>
    <%= f.text_field :sbn %>
  </div>
  <div class="field">
    <%= f.label :autor %><br>
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :idioma %><br>
    <%= f.text_field :idioma %>
  </div>
  <div class="field">
    <%= f.label :paginacao %><br>
    <%= f.text_field :paginacao %>
  </div>
  <div class="field">
    <%= f.label :imprenta %><br>
    <%= f.text_field :imprenta %>
  </div>
  <div class="field">
    <%= f.label :palavras %><br>
    <%= f.text_field :palavras %>
  </div>
  <div class="field">
    <%= f.label :chave %><br>
    <%= f.text_area :chave %>
  </div>
  <div class="field">
    <%= f.label :data_cadastro %><br>
    <%= f.datetime_select :data_cadastro %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/livros/edit.html.erb
<h1>Editing Livro</h1>

<%= render 'form' %>

<%= link_to 'Show', @livro %> |
<%= link_to 'Back', livros_path %>

app/views/livros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Livros</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Nome</th>
      <th>Descricao</th>
      <th>Codigo</th>
      <th>Sbn</th>
      <th>Autor</th>
      <th>Idioma</th>
      <th>Paginacao</th>
      <th>Imprenta</th>
      <th>Palavras</th>
      <th>Chave</th>
      <th>Data cadastro</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @livros.each do |livro| %>
      <tr>
        <td><%= livro.titulo %></td>
        <td><%= livro.nome %></td>
        <td><%= livro.descricao %></td>
        <td><%= livro.codigo %></td>
        <td><%= livro.sbn %></td>
        <td><%= livro.autor %></td>
        <td><%= livro.idioma %></td>
        <td><%= livro.paginacao %></td>
        <td><%= livro.imprenta %></td>
        <td><%= livro.palavras %></td>
        <td><%= livro.chave %></td>
        <td><%= livro.data_cadastro %></td>
        <div class="btn-group pull-right">
	  <td class="btn btn-default btn-sm"><%= link_to 'Exibir', livro %></td>
	  <td class="btn btn-default btn-sm"><%= link_to 'Editar', edit_livro_path(livro) %></td>
	  <td class="btn btn-default btn-sm"><%= link_to 'Deletar', livro, method: :delete, data: { confirm: 'Esta certo disso?' } %></td>
	<div>  
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Livro', new_livro_path, class: 'btn btn-primary' %>

app/views/livros/new.html.erb
<h1>New Livro</h1>

<%= render 'form' %>

<%= link_to 'Back', livros_path %>

app/views/livros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @livro.titulo %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @livro.nome %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @livro.descricao %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @livro.codigo %>
</p>

<p>
  <strong>Sbn:</strong>
  <%= @livro.sbn %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @livro.autor %>
</p>

<p>
  <strong>Idioma:</strong>
  <%= @livro.idioma %>
</p>

<p>
  <strong>Paginacao:</strong>
  <%= @livro.paginacao %>
</p>

<p>
  <strong>Imprenta:</strong>
  <%= @livro.imprenta %>
</p>

<p>
  <strong>Palavras:</strong>
  <%= @livro.palavras %>
</p>

<p>
  <strong>Chave:</strong>
  <%= @livro.chave %>
</p>

<p>
  <strong>Data cadastro:</strong>
  <%= @livro.data_cadastro %>
</p>

<%= link_to 'Edit', edit_livro_path(@livro) %> |
<%= link_to 'Back', livros_path %>

app/views/usuarios/_form.html.erb
<%= simple_form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :matricula %><br>
    <%= f.text_field :matricula %>
  </div>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :sobrenome %><br>
    <%= f.text_field :sobrenome %>
  </div>
  <div class="field">
    <%= f.label :endereco %><br>
    <%= f.text_field :endereco %>
  </div>
  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.text_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Matricula</th>
      <th>Nome</th>
      <th>Sobrenome</th>
      <th>Endereco</th>
      <th>String</th>
      <th>Telefone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.matricula %></td>
        <td><%= usuario.nome %></td>
        <td><%= usuario.sobrenome %></td>
        <td><%= usuario.endereco %></td>
        <td><%= usuario.string %></td>
        <td><%= usuario.telefone %></td>
        <td><%= usuario.email %></td>
        <div class="btn-group pull-right">
	  <td class="btn btn-default btn-sm"><%= link_to 'Exibir', usuario %></td>
	  <td class="btn btn-default btn-sm"><%= link_to 'Editar', edit_usuario_path(usuario) %></td>
	  <td class="btn btn-default btn-sm"><%= link_to 'Deletar', usuario, method: :delete, data: { confirm: 'Esta certo disso?' } %></td>
        <div>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Usuario', new_usuario_path, class: 'btn btn-primary' %>

app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Matricula:</strong>
  <%= @usuario.matricula %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @usuario.nome %>
</p>

<p>
  <strong>Sobrenome:</strong>
  <%= @usuario.sobrenome %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @usuario.endereco %>
</p>

<p>
  <strong>String:</strong>
  <%= @usuario.string %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @usuario.telefone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>